name: Update README with Hashnode Blogs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    outputs:
      changes_found: ${{ steps.check_changes.outputs.changes_found }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install prettier

      - name: Fetch Hashnode Blogs and Update README
        run: node scripts/updateReadme.js

      - name: Check for Changes in README
        id: check_changes
        run: |
          git diff --quiet README.md || echo "changes_found=true" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes_found == 'true'
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with Hashnode Blogs"
          git push
